name: ios_fl_n_antifish_3408
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  logger: ^2.5.0
  flutter_bloc: ^9.0.0
  font_awesome_flutter: ^10.8.0
  share_plus: ^11.0.0
  equatable: ^2.0.5
  collection: ^1.18.0
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.1
  permission_handler: ^10.4.0
  flutter_native_splash: ^2.4.5
  onesignal_flutter: ^5.1.2
  appsflyer_sdk: ^6.15.2
  http: ^1.2.1
  advertising_id: ^2.0.0
  flutter_inappwebview: ^6.1.5
  external_app_launcher: ^4.0.3
  app_tracking_transparency: ^2.0.6+1
  device_info_plus: ^11.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/onboarding/
