name: ios_fl_n_antifish_3408
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  logger: ^2.5.0
  flutter_bloc: ^9.0.0
  font_awesome_flutter: ^10.8.0
  share_plus: ^11.0.0
  equatable: ^2.0.5
  collection: ^1.18.0
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/onboarding/
